shuffle: false
model_name: "l2p"
backbone_type: "vit_base_patch16_224_l2p"
get_original_backbone: true
device: "0"
seed: 1993

tuned_epoch: 60
init_lr: 0.0003
batch_size: 16
weight_decay: 0
min_lr: 1e-5
optimizer: "adam"
scheduler: "constant"
reinit_optimizer: true

global_pool: "token"
head_type: "prompt"
freeze:
  - "blocks"
  - "patch_embed"
  - "cls_token"
  - "norm"
  - "pos_embed"

pretrained: true
drop: 0.0
drop_path: 0.0

prompt_pool: true
size: 10
length: 5
top_k: 5
initializer: "uniform"
prompt_key: true
prompt_key_init: "uniform"
use_prompt_mask: false
shared_prompt_pool: false
shared_prompt_key: false
batchwise_prompt: true
embedding_key: "cls"
predefined_key: ""
pull_constraint: true
pull_constraint_coeff: 0.1

K: 5
split_mode: 'k_fold'
img_size: 224
nb_classes: 23
dataset: 'iMER'